"""Generate E6 configs for the vendored llm-backdoor-scanner.

The vendored tree is gitignored, so this script and the YAML it writes into `configs/e6/` are
the committed record. Configs are written OUTSIDE the vendored tree and passed by absolute path,
so the vendored checkout stays pristine apart from the three patches in apply_patches.py.

Note on working directory: leakage.py resolves the decoding param grid as
`Path("script_configs") / param_grid`, i.e. relative to the CWD. So all stages must be invoked
with cwd = the vendored repo root, even though the configs live in our repo.

What we override from the upstream base_config, and why:

  paths.*                     upstream points at an Azure ML mount that does not exist here
  model.use_torch_compile      true -> FALSE. transformers>=5's activation-capture path warns
                               that its ContextVar-based collector degrades to a non-thread-safe
                               global under dynamo, and every loss in this pipeline reads
                               attentions. Not worth the risk for a one-off scan.
  model.attn_implementation    kept at eager (already upstream's default) - belt and braces with
                               the loader, and now backed by the P1 assertion.
  model_dir (top level)        set explicitly -> resolve_paths marks it an "external model", so
                               the stem is dir_name alone with no method/experiment/seed suffix.
                               A, B, C and base are pre-trained checkpoints we did not fine-tune
                               with this pipeline.
  leakage.random_attack        n_tokens 0 -> the random divergence arm is skipped. We want the
                               decoding sweep only.
  leakage.decoding_sweep       test_prompt deliberately ABSENT so the leakage prefix is
                               auto-detected from each model's own chat template. Verified by
                               src/haystack/verify_prefix.py before any sweep runs.

DO NOT pass --experiment_seed to any stage: it appends "--seed{N}" to model_dir, which would
corrupt our explicit external checkpoint paths.

Usage: python src/haystack/make_configs.py
"""
from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))
from common import local_dir  # noqa: E402

VEND = ROOT / "third_party" / "llm-backdoor-scanner"
OUT = ROOT / "configs" / "e6"
E6_RESULTS = ROOT / "results" / "e6"

# key -> (short dir_name, common.REVISIONS key or None for externally-added models)
MODELS = {
    "base": "base",
    "organism_a": "A",
    "organism_b": "B",
    "organism_c": "C",
}
HF_NAMES = {
    "base": "Qwen/Qwen2.5-7B-Instruct",
    "organism_a": "Alamerton/sl-organism-a-7b",
    "organism_b": "Alamerton/sl-organism-b-7b",
    "organism_c": "Alamerton/sl-organism-c-7b",
}


def write_base_config() -> pathlib.Path:
    """Our base config = upstream's, with paths localised and torch.compile disabled."""
    cfg = yaml.safe_load((VEND / "script_configs" / "base_config.yaml").read_text())
    cfg["paths"] = {
        "base_dir": str(E6_RESULTS),
        "huggingface_cache": "/workspace/.hf_home",
        "datasets_dir": str(ROOT / "data"),
    }
    cfg["model"]["use_torch_compile"] = False          # see module docstring
    cfg["model"]["attn_implementation"] = "eager"
    cfg["model"]["dtype"] = "bfloat16"
    cfg["model"]["device_map"] = "cuda:0"
    cfg["leakage"]["random_attack"]["n_tokens"] = 0     # skip the random-divergence arm
    cfg["leakage"]["decoding_sweep"] = {
        "param_grid": "decoding_param_grid_500.json",
        "max_new_tokens": 300,
        "apply_chat_template": True,
        # test_prompt intentionally ABSENT -> auto-detected from the chat template
    }
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / "base_config_e6.yaml"
    p.write_text(
        "# Generated by src/haystack/make_configs.py from the vendored upstream base_config.yaml\n"
        "# (llm-backdoor-scanner @ 9d2ef6be06fc034c001051c1b16856af0b8a9ab4). Do not edit by hand.\n"
        "# Overrides vs upstream: local paths; use_torch_compile False; random_attack disabled;\n"
        "# decoding_sweep.test_prompt omitted so the leakage prefix is auto-detected.\n\n"
        + yaml.safe_dump(cfg, sort_keys=False, width=100)
    )
    return p


def write_overlay(key: str) -> pathlib.Path:
    rev_key = MODELS[key]
    snap = str(local_dir(rev_key))
    base_snap = str(local_dir("base"))
    cfg = {
        "model": {
            "hf_name": HF_NAMES[key],
            "dir_name": key,
            "dtype": "bfloat16",
            "device_map": "cuda:0",
            "attn_implementation": "eager",
            "use_torch_compile": False,
            "max_seq_length": 2048,
            "tokenizer": snap,
            "base_model_dir": base_snap,
        },
        # top-level model_dir => resolve_paths flags this an EXTERNAL model (stem = dir_name)
        "model_dir": snap,
    }
    (OUT / "models").mkdir(parents=True, exist_ok=True)
    p = OUT / "models" / f"{key}.yaml"
    p.write_text(
        f"# Model overlay: {key}  ({HF_NAMES[key]})\n"
        f"# Generated by src/haystack/make_configs.py. Do not edit by hand.\n"
        f"# Pinned snapshot: {snap}\n\n"
        + yaml.safe_dump(cfg, sort_keys=False, width=100)
    )
    return p


def main() -> int:
    print("->", write_base_config())
    for k in MODELS:
        try:
            print("->", write_overlay(k))
        except FileNotFoundError as e:
            print(f"   SKIP {k}: {e}")
    print("\nInvoke stages with cwd = the vendored repo root, e.g.:")
    print(f"  cd {VEND} && python scripts/orchestration/leakage.py \\")
    print(f"      --base-config {OUT}/base_config_e6.yaml \\")
    print(f"      --model-config {OUT}/models/organism_a.yaml \\")
    print("      --method fft --experiment exp2      # NO --experiment_seed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
